### ISSUE TITLE
Empty Output Table

### ISSUE THREAD

**Issue by Wikkiee** [ManojTGN/ascii-table#1]
When having an invalid parameter or an argument, an empty ASCII output table is generated
![Capture](https://github.com/ManojTGN/ascii-table/assets/70148919/1b7e58da-fa7d-4e4a-b824-1ac0c11533e1)

**Comment by ManojTGN** [comment]
### Fixed This Specific Issue (fb4ac69)
When There Is No Input Content, It Is Set To `"\0"` For Debugging.., It Was Never Changed And So It Caused This Issue.
And It Is Fixed Now In The Mentioned Commit.

Thank You♥
