### ISSUE TITLE
Table Line Alignment Problem

### ISSUE THREAD

**Issue by Medhunraj** [ManojTGN/ascii-table#2]
**Describe the bug**
Using essential parameters like hex, oct, dec the output table top and bottom line are mismatching with the content. I have attached the problem as a image below

**To Reproduce**
1. use `--hex` or `--oct` or `--dec` parameter
2. and try to give input content of a length greater than 32 or use parameter `--alphas --digits` which will be enough to produce this error

**Expected behavior**
Alignment of the line should match with the content produced in the output

**Screenshots**
![Capture](https://github.com/ManojTGN/ascii-table/assets/104486882/650f9510-aaaf-4013-a8bb-247486b83705)

**Desktop (please complete the following information):**
 - OS: Windows
 - Terminal Command Prompt
 - Version 0.3.2

**Additional context**
And the parameter `--oct` is working instead of `--octa`

**Comment by ManojTGN** [comment]
## Fixed Table Alignment ( 9a4a0fe )
- Fixed The Top & Bottom Line Alignment
- Fixed The `--octa` parameter name issue
