### ISSUE TITLE
Binary Format

### ISSUE THREAD

**Issue by allansam27** [ManojTGN/ascii-table#4]
**Is your feature request related to a problem? Please describe.**
No.

**Describe the solution you'd like**
This project is extremely helpful to me working on ascii! and i always finds difficult to view / convert the ascii to binary for my work and it will lot more nice to add binary representation into the output table.

**Describe alternatives you've considered**
I know it will occupy the space and the table will become ugly but rather directly adding it, may be give it like a optional parameter like `--binary` or `--bin` ex: (`--hex`,`--octa`,`--dec`). so that if the user requires to see the binary data he may view it by adding this parameter.

**Comment by ManojTGN** [comment]
## Feature Added ( 82c948c )
Thanks For The Feature Request And I Have Added The Binary Representation. Now You Can Use The `--bin` Parameter To Show The Binary Representation. <3

**Comment by allansam27** [comment]
**Thanks a lot** @ManojTGN for adding the binary representation! I will build and try it out myself until you make the release
